version: "3"
services:
  mysql:
    image: sr1994lu/mysql:latest
    container_name: "mysql"
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_DATABASE: ma4299db01
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  tomcat:
    image: sr1994lu/tomcat:latest
    container_name: "tomcat"
    tty: true
    ports:
      - 8888:8080
networks:
  default:
